Bootstrap: docker
From: debian:buster

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-miller
    COPYRIGHT Copyright © 2023 Pittsburgh Supercomputing Center. All Rights Reserved.  
    VERSION 6.9.0

%post
    apt update
    apt install -y wget
    cd /tmp 
    wget -nc https://github.com/johnkerl/miller/releases/download/v6.9.0/miller-6.9.0-linux-amd64.deb
    dpkg -i miller-6.9.0-linux-amd64.deb

%runscript
    mlr "$@"
