Bootstrap: docker
From: debian:buster

%labels
    MAINTAINER icaoberg
    EMAIL icaoberg@psc.edu
    SUPPORT help@psc.edu
    REPOSITORY http://gitub.com/pscedu/singularity-miller
    COPYRIGHT Copyright © 2023 Pittsburgh Supercomputing Center. All Rights Reserved.  
    VERSION 5.4.0-1

%post
    apt update
    apt install -y miller

%runscript
    mlr "$@"
